#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 1 ]]; then
  echo "usage: $0 <experiment_dir_name>" >&2
  exit 2
fi

EXP_NAME="$1"
ROOT_DIR="/home/user/图片"
REPO_DIR="/home/user/图片/gsm8k_training_repo"
SCRIPT_PATH="/home/user/图片/gsm8k_training_repo/llama3_1_(8b)_grpo.py"
OUTPUT_DIR="${OUTPUT_DIR:-$ROOT_DIR/gsm8k_improved/$EXP_NAME}"
STDOUT_LOG="$OUTPUT_DIR/stdout.log"
PID_FILE="$OUTPUT_DIR/run.pid"
EARLY_STOP_NOTE="$OUTPUT_DIR/early_stop.txt"

: "${RUN_MODE:=single}"
: "${RUN_PROTOCOL:=standard}"
: "${TRAINING_METHOD:=grpo}"
: "${EVAL_ONLY:=1}"
: "${SKIP_EVAL_BEFORE:=0}"
: "${SKIP_EVAL_WARMUP:=0}"
: "${SKIP_SAMPLE_GENERATION:=1}"
: "${SAVE_ADAPTER:=1}"
: "${WRITE_EXPLANATION:=0}"
: "${SAVE_RERANK_CANDIDATES:=0}"
: "${AUTO_SYNC_GIT_REPO:=0}"
: "${DATASET_SOURCE:=gsm8k}"
: "${DATASET_SPLIT:=train}"
: "${TRAIN_VALIDATION_MOD:=0}"
: "${TRAIN_VALIDATION_BUCKET:=0}"
: "${DATASET_CONFIG:=main}"
: "${DATASET_START_INDEX:=0}"
: "${MAX_TRAIN_SAMPLES:=1000}"
: "${NUM_EVAL_SAMPLES:=200}"
: "${RANDOM_SEED:=42}"
: "${MODEL_NAME:=Qwen/Qwen2.5-0.5B-Instruct}"
: "${MAX_STEPS:=100}"
: "${MAX_SEQ_LENGTH:=512}"
: "${MAX_PROMPT_LENGTH:=256}"
: "${NUM_GENERATIONS:=4}"
: "${PER_DEVICE_TRAIN_BATCH_SIZE:=4}"
: "${LEARNING_RATE:=2e-5}"
: "${GRPO_BETA:=0.0}"
: "${GRPO_EPSILON:=0.2}"
: "${GRPO_WARMUP_RATIO:=0.1}"
: "${GRPO_MAX_GRAD_NORM:=0.1}"
: "${GRPO_IMPORTANCE_SAMPLING_LEVEL:=token}"
: "${GRPO_SCALE_REWARDS:=group}"
: "${GRPO_LOSS_TYPE:=dapo}"
: "${MASK_TRUNCATED_COMPLETIONS:=0}"
: "${TOP_ENTROPY_QUANTILE:=1.0}"

: "${EVAL_USE_CONFIDENCE_RERANK:=1}"
: "${EVAL_NUM_CANDIDATES:=8}"
: "${EVAL_RERANK_TEMPERATURE:=0.65}"
: "${EVAL_RERANK_TOP_P:=0.92}"
: "${EVAL_EXPAND_CANDIDATES:=0}"
: "${EVAL_EXPAND_CANDIDATES_EXTRA:=8}"
: "${EVAL_EXPAND_MULTI_PROFILE:=0}"
: "${EVAL_EXPAND_MIN_UNIQUE_ANSWERS:=4}"
: "${EVAL_EXPAND_MAX_TOP_CONSENSUS:=2}"
: "${EVAL_EXPAND_TOP_SCORE_GAP:=0.08}"
: "${EVAL_EXPAND_REQUIRE_PASS_DIVERSITY:=0}"
: "${EVAL_EXPAND_MIN_DISTINCT_PASSES:=2}"
: "${EVAL_EXPAND_REQUIRE_BASE_PASS_SUPPORT:=0}"
: "${EVAL_USE_SCOUT_HINTS:=0}"

: "${CONFIDENCE_WEIGHT:=1.0}"
: "${CONSENSUS_WEIGHT:=0.35}"
: "${FORMAT_WEIGHT:=0.15}"
: "${LOW_CONFIDENCE_PROB_THRESHOLD:=0.25}"
: "${LOW_CONFIDENCE_WEIGHT:=0.35}"
: "${NOVELTY_WEIGHT:=0.1}"
: "${ANSWER_AGG_COUNT_WEIGHT:=0.85}"
: "${ANSWER_AGG_STRICT_WEIGHT:=0.2}"
: "${ANSWER_AGG_EQUATION_WEIGHT:=0.25}"
: "${ANSWER_AGG_DIVERSITY_WEIGHT:=0.08}"
: "${ANSWER_AGG_LOW_CONF_WEIGHT:=0.2}"
: "${ANSWER_AGG_MIN_GROUP_SIZE:=2}"
: "${ANSWER_AGG_MARGIN:=0.24}"
: "${ANSWER_AGG_PAIR_COUNT_WEIGHT:=0.45}"
: "${ANSWER_AGG_PAIR_MAX_SINGLE_GAP:=0.12}"

: "${VERIFIER_BUNDLE_PATH:=/home/user/图片/gsm8k_improved/verifier_model_v3_pairwise_hybrid_c05/verifier_bundle.pkl}"
: "${VERIFIER_SCORE_WEIGHT:=0.2}"
: "${VERIFIER_TIE_MARGIN:=0.15}"
: "${VERIFIER_MIN_CANDIDATES:=2}"
: "${VERIFIER_REQUIRE_ANSWER_DISAGREEMENT:=1}"
: "${RERANKER_BUNDLE_PATH:=/home/user/图片/gsm8k_improved/reranker_model_v2_pointwise_c2/reranker_bundle.pkl}"
: "${ENABLE_RERANKER_NEAR_TOP_OVERRIDE:=1}"
: "${RERANKER_NEAR_TOP_MARGIN:=0.35}"
: "${RERANKER_NEAR_TOP_MIN_SCORE:=0.0}"
: "${ADAPTER_PATH:=/home/user/图片/outputs_llama3_1_grpo_gsm8k_rerank_eval/adapter}"
: "${HF_LOCAL_FILES_ONLY:=1}"

: "${PROMPT_TEMPLATE_MODE:=xml_default}"
: "${ANSWER_EXTRACTION_MODE:=xml_or_last_number}"
: "${ENABLE_DATA_QUALITY_FILTER:=0}"
: "${DATA_QUALITY_KEEP_RATIO:=1.0}"
: "${DATA_QUALITY_POLICY:=balanced}"
: "${DATA_QUALITY_MIN_SCORE:=}"

: "${BEST_EXACT_MATCH_RATE:=0.565}"
: "${EARLY_STOP_SAMPLE:=40}"
: "${EARLY_STOP_DELTA:=0.05}"
: "${EARLY_STOP_ENABLE:=1}"

mkdir -p "$OUTPUT_DIR"
rm -f "$EARLY_STOP_NOTE"

(
  cd "$ROOT_DIR"
  env \
    RUN_MODE="$RUN_MODE" \
    RUN_PROTOCOL="$RUN_PROTOCOL" \
    TRAINING_METHOD="$TRAINING_METHOD" \
    EVAL_ONLY="$EVAL_ONLY" \
    SKIP_EVAL_BEFORE="$SKIP_EVAL_BEFORE" \
    SKIP_EVAL_WARMUP="$SKIP_EVAL_WARMUP" \
    SKIP_SAMPLE_GENERATION="$SKIP_SAMPLE_GENERATION" \
    SAVE_ADAPTER="$SAVE_ADAPTER" \
    WRITE_EXPLANATION="$WRITE_EXPLANATION" \
    SAVE_RERANK_CANDIDATES="$SAVE_RERANK_CANDIDATES" \
    AUTO_SYNC_GIT_REPO="$AUTO_SYNC_GIT_REPO" \
    DATASET_SOURCE="$DATASET_SOURCE" \
    DATASET_SPLIT="$DATASET_SPLIT" \
    TRAIN_VALIDATION_MOD="$TRAIN_VALIDATION_MOD" \
    TRAIN_VALIDATION_BUCKET="$TRAIN_VALIDATION_BUCKET" \
    DATASET_CONFIG="$DATASET_CONFIG" \
    DATASET_START_INDEX="$DATASET_START_INDEX" \
    MAX_TRAIN_SAMPLES="$MAX_TRAIN_SAMPLES" \
    NUM_EVAL_SAMPLES="$NUM_EVAL_SAMPLES" \
    RANDOM_SEED="$RANDOM_SEED" \
    MODEL_NAME="$MODEL_NAME" \
    MAX_STEPS="$MAX_STEPS" \
    MAX_SEQ_LENGTH="$MAX_SEQ_LENGTH" \
    MAX_PROMPT_LENGTH="$MAX_PROMPT_LENGTH" \
    NUM_GENERATIONS="$NUM_GENERATIONS" \
    PER_DEVICE_TRAIN_BATCH_SIZE="$PER_DEVICE_TRAIN_BATCH_SIZE" \
    LEARNING_RATE="$LEARNING_RATE" \
    GRPO_BETA="$GRPO_BETA" \
    GRPO_EPSILON="$GRPO_EPSILON" \
    GRPO_WARMUP_RATIO="$GRPO_WARMUP_RATIO" \
    GRPO_MAX_GRAD_NORM="$GRPO_MAX_GRAD_NORM" \
    GRPO_IMPORTANCE_SAMPLING_LEVEL="$GRPO_IMPORTANCE_SAMPLING_LEVEL" \
    GRPO_SCALE_REWARDS="$GRPO_SCALE_REWARDS" \
    GRPO_LOSS_TYPE="$GRPO_LOSS_TYPE" \
    MASK_TRUNCATED_COMPLETIONS="$MASK_TRUNCATED_COMPLETIONS" \
    TOP_ENTROPY_QUANTILE="$TOP_ENTROPY_QUANTILE" \
    EVAL_USE_CONFIDENCE_RERANK="$EVAL_USE_CONFIDENCE_RERANK" \
    EVAL_NUM_CANDIDATES="$EVAL_NUM_CANDIDATES" \
    EVAL_RERANK_TEMPERATURE="$EVAL_RERANK_TEMPERATURE" \
    EVAL_RERANK_TOP_P="$EVAL_RERANK_TOP_P" \
    EVAL_EXPAND_CANDIDATES="$EVAL_EXPAND_CANDIDATES" \
    EVAL_EXPAND_CANDIDATES_EXTRA="$EVAL_EXPAND_CANDIDATES_EXTRA" \
    EVAL_EXPAND_MULTI_PROFILE="$EVAL_EXPAND_MULTI_PROFILE" \
    EVAL_EXPAND_MIN_UNIQUE_ANSWERS="$EVAL_EXPAND_MIN_UNIQUE_ANSWERS" \
    EVAL_EXPAND_MAX_TOP_CONSENSUS="$EVAL_EXPAND_MAX_TOP_CONSENSUS" \
    EVAL_EXPAND_TOP_SCORE_GAP="$EVAL_EXPAND_TOP_SCORE_GAP" \
    EVAL_EXPAND_REQUIRE_PASS_DIVERSITY="$EVAL_EXPAND_REQUIRE_PASS_DIVERSITY" \
    EVAL_EXPAND_MIN_DISTINCT_PASSES="$EVAL_EXPAND_MIN_DISTINCT_PASSES" \
    EVAL_EXPAND_REQUIRE_BASE_PASS_SUPPORT="$EVAL_EXPAND_REQUIRE_BASE_PASS_SUPPORT" \
    EVAL_USE_SCOUT_HINTS="$EVAL_USE_SCOUT_HINTS" \
    CONFIDENCE_WEIGHT="$CONFIDENCE_WEIGHT" \
    CONSENSUS_WEIGHT="$CONSENSUS_WEIGHT" \
    FORMAT_WEIGHT="$FORMAT_WEIGHT" \
    LOW_CONFIDENCE_PROB_THRESHOLD="$LOW_CONFIDENCE_PROB_THRESHOLD" \
    LOW_CONFIDENCE_WEIGHT="$LOW_CONFIDENCE_WEIGHT" \
    NOVELTY_WEIGHT="$NOVELTY_WEIGHT" \
    ANSWER_AGG_COUNT_WEIGHT="$ANSWER_AGG_COUNT_WEIGHT" \
    ANSWER_AGG_STRICT_WEIGHT="$ANSWER_AGG_STRICT_WEIGHT" \
    ANSWER_AGG_EQUATION_WEIGHT="$ANSWER_AGG_EQUATION_WEIGHT" \
    ANSWER_AGG_DIVERSITY_WEIGHT="$ANSWER_AGG_DIVERSITY_WEIGHT" \
    ANSWER_AGG_LOW_CONF_WEIGHT="$ANSWER_AGG_LOW_CONF_WEIGHT" \
    ANSWER_AGG_MIN_GROUP_SIZE="$ANSWER_AGG_MIN_GROUP_SIZE" \
    ANSWER_AGG_MARGIN="$ANSWER_AGG_MARGIN" \
    ANSWER_AGG_PAIR_COUNT_WEIGHT="$ANSWER_AGG_PAIR_COUNT_WEIGHT" \
    ANSWER_AGG_PAIR_MAX_SINGLE_GAP="$ANSWER_AGG_PAIR_MAX_SINGLE_GAP" \
    VERIFIER_BUNDLE_PATH="$VERIFIER_BUNDLE_PATH" \
    VERIFIER_SCORE_WEIGHT="$VERIFIER_SCORE_WEIGHT" \
    VERIFIER_TIE_MARGIN="$VERIFIER_TIE_MARGIN" \
    VERIFIER_MIN_CANDIDATES="$VERIFIER_MIN_CANDIDATES" \
    VERIFIER_REQUIRE_ANSWER_DISAGREEMENT="$VERIFIER_REQUIRE_ANSWER_DISAGREEMENT" \
    RERANKER_BUNDLE_PATH="$RERANKER_BUNDLE_PATH" \
    ENABLE_RERANKER_NEAR_TOP_OVERRIDE="$ENABLE_RERANKER_NEAR_TOP_OVERRIDE" \
    RERANKER_NEAR_TOP_MARGIN="$RERANKER_NEAR_TOP_MARGIN" \
    RERANKER_NEAR_TOP_MIN_SCORE="$RERANKER_NEAR_TOP_MIN_SCORE" \
    ADAPTER_PATH="$ADAPTER_PATH" \
    OUTPUT_DIR="$OUTPUT_DIR" \
    HF_LOCAL_FILES_ONLY="$HF_LOCAL_FILES_ONLY" \
    PROMPT_TEMPLATE_MODE="$PROMPT_TEMPLATE_MODE" \
    ANSWER_EXTRACTION_MODE="$ANSWER_EXTRACTION_MODE" \
    ENABLE_DATA_QUALITY_FILTER="$ENABLE_DATA_QUALITY_FILTER" \
    DATA_QUALITY_KEEP_RATIO="$DATA_QUALITY_KEEP_RATIO" \
    DATA_QUALITY_POLICY="$DATA_QUALITY_POLICY" \
    DATA_QUALITY_MIN_SCORE="$DATA_QUALITY_MIN_SCORE" \
    python3 "$SCRIPT_PATH" > "$STDOUT_LOG" 2>&1
) &

RUN_PID=$!
echo "$RUN_PID" > "$PID_FILE"

THRESHOLD=$(python3 - <<PY
best = float("$BEST_EXACT_MATCH_RATE")
delta = float("$EARLY_STOP_DELTA")
print(best - delta)
PY
)

echo "[runner] pid=$RUN_PID threshold=$THRESHOLD sample=$EARLY_STOP_SAMPLE output_dir=$OUTPUT_DIR"

if [[ "$EARLY_STOP_ENABLE" != "1" ]]; then
  wait "$RUN_PID"
  exit $?
fi

while kill -0 "$RUN_PID" 2>/dev/null; do
  if [[ -f "$STDOUT_LOG" ]]; then
    MATCH_LINE=$(python3 - <<PY
import re
from pathlib import Path
log = Path("$STDOUT_LOG")
target = int("$EARLY_STOP_SAMPLE")
pattern = re.compile(rf"\\[progress\\] .*: {target}/\\d+ \\(exact_matches=(\\d+)\\)")
last = None
for line in log.read_text(errors="ignore").splitlines():
    match = pattern.search(line)
    if match:
        last = match.group(1)
if last is not None:
    print(last)
PY
)
    if [[ -n "${MATCH_LINE:-}" ]]; then
      RATE=$(python3 - <<PY
exact = int("$MATCH_LINE")
sample = int("$EARLY_STOP_SAMPLE")
print(exact / sample)
PY
)
      SHOULD_STOP=$(python3 - <<PY
rate = float("$RATE")
threshold = float("$THRESHOLD")
print("1" if rate < threshold else "0")
PY
)
      if [[ "$SHOULD_STOP" == "1" ]]; then
        {
          echo "early_stop_sample=$EARLY_STOP_SAMPLE"
          echo "exact_matches=$MATCH_LINE"
          echo "observed_rate=$RATE"
          echo "threshold=$THRESHOLD"
        } | tee "$EARLY_STOP_NOTE"
        kill "$RUN_PID" 2>/dev/null || true
        wait "$RUN_PID" || true
        exit 10
      fi
      break
    fi
  fi
  sleep 15
done

wait "$RUN_PID"
